// This file is auto-generated by @hey-api/openapi-ts

export const ActionLogSchema = {
    properties: {
        action: {
            type: 'string',
            maxLength: 1024,
            title: 'Action'
        }
    },
    type: 'object',
    required: ['action'],
    title: 'ActionLog'
} as const;

export const ActionLogPublicSchema = {
    properties: {
        user: {
            type: 'string',
            title: 'User'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Timestamp'
        }
    },
    type: 'object',
    required: ['user', 'action', 'timestamp'],
    title: 'ActionLogPublic'
} as const;

export const ActionLogsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ActionLogPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ActionLogsPublic'
} as const;

export const AdminSettingsPublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        value: {
            type: 'string',
            title: 'Value'
        }
    },
    type: 'object',
    required: ['name', 'value'],
    title: 'AdminSettingsPublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_templates_create_templateSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_templates-create_template'
} as const;

export const Body_templates_update_templateSchema = {
    properties: {
        file: {
            anyOf: [
                {
                    type: 'string',
                    format: 'binary'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File'
        }
    },
    type: 'object',
    title: 'Body_templates-update_template'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const IntakeDocumentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        template_id: {
            type: 'string',
            title: 'Template Id'
        },
        form_name: {
            type: 'string',
            title: 'Form Name'
        },
        category: {
            type: 'string',
            title: 'Category'
        },
        filename: {
            type: 'string',
            title: 'Filename'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        packet_id: {
            type: 'string',
            format: 'uuid',
            title: 'Packet Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'template_id', 'form_name', 'category', 'filename', 'status', 'packet_id'],
    title: 'IntakeDocumentPublic'
} as const;

export const IntakePacketCreateSchema = {
    properties: {
        patient_id_number: {
            type: 'string',
            maxLength: 20,
            title: 'Patient Id Number'
        },
        patient_name: {
            type: 'string',
            maxLength: 255,
            title: 'Patient Name'
        },
        facility: {
            type: 'string',
            maxLength: 50,
            title: 'Facility'
        },
        admission_date: {
            type: 'string',
            maxLength: 20,
            title: 'Admission Date'
        },
        counselor_name: {
            type: 'string',
            maxLength: 255,
            title: 'Counselor Name'
        },
        template_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Template Ids'
        }
    },
    type: 'object',
    required: ['patient_id_number', 'patient_name', 'facility', 'admission_date', 'counselor_name', 'template_ids'],
    title: 'IntakePacketCreate'
} as const;

export const IntakePacketPublicSchema = {
    properties: {
        patient_id_number: {
            type: 'string',
            maxLength: 20,
            title: 'Patient Id Number'
        },
        patient_name: {
            type: 'string',
            maxLength: 255,
            title: 'Patient Name'
        },
        facility: {
            type: 'string',
            maxLength: 50,
            title: 'Facility'
        },
        admission_date: {
            type: 'string',
            maxLength: 20,
            title: 'Admission Date'
        },
        counselor_name: {
            type: 'string',
            maxLength: 255,
            title: 'Counselor Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        documents: {
            items: {
                '$ref': '#/components/schemas/IntakeDocumentPublic'
            },
            type: 'array',
            title: 'Documents',
            default: []
        }
    },
    type: 'object',
    required: ['patient_id_number', 'patient_name', 'facility', 'admission_date', 'counselor_name', 'id', 'status', 'owner_id'],
    title: 'IntakePacketPublic'
} as const;

export const IntakePacketsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/IntakePacketPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'IntakePacketsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PatientSchema = {
    properties: {
        ehr_id: {
            type: 'integer',
            title: 'EHR Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        counselorId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Counselorid'
        }
    },
    type: 'object',
    required: ['ehr_id'],
    title: 'Patient'
} as const;

export const PatientCreateSchema = {
    properties: {
        ehr_id: {
            type: 'integer',
            title: 'EHR Id'
        }
    },
    type: 'object',
    required: ['ehr_id'],
    title: 'PatientCreate'
} as const;

export const PatientPublicSchema = {
    properties: {
        ehr_id: {
            type: 'integer',
            title: 'EHR Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['ehr_id', 'id'],
    title: 'PatientPublic'
} as const;

export const PatientsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PatientPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PatientsPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ReminderPatientPayloadSchema = {
    properties: {
        ehr_id: {
            type: 'integer',
            title: 'EHR Id'
        }
    },
    type: 'object',
    required: ['ehr_id'],
    title: 'ReminderPatientPayload'
} as const;

export const ReminderStateSchema = {
    properties: {
        key: {
            type: 'string',
            maxLength: 100,
            title: 'Key'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        seen_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seen At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        patient_ehr_id: {
            type: 'integer',
            title: 'Patient EHR Id'
        }
    },
    type: 'object',
    required: ['key', 'patient_ehr_id'],
    title: 'ReminderState',
    description: 'Per-patient (ehr_id), per-reminder state.'
} as const;

export const TemplatePublicSchema = {
    properties: {
        file_id: {
            type: 'string',
            format: 'uuid',
            title: 'File Id'
        },
        file_name: {
            type: 'string',
            title: 'File Name'
        },
        file_modified: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Modified'
        },
        file_owner: {
            type: 'string',
            format: 'uuid',
            title: 'File Owner'
        }
    },
    type: 'object',
    required: ['file_id', 'file_name', 'file_owner'],
    title: 'TemplatePublic'
} as const;

export const TemplatesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TemplatePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TemplatesPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        role: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;