// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";
import type {
	AdminReadFolderResponse,
	AdminUpdateFolderData,
	AdminUpdateFolderResponse,
	FormsCreateIntakePacketData,
	FormsCreateIntakePacketResponse,
	FormsDeletePacketData,
	FormsDeletePacketResponse,
	FormsGetDocumentPdfData,
	FormsGetDocumentPdfResponse,
	FormsListTemplatesResponse,
	FormsReadDocumentData,
	FormsReadDocumentResponse,
	FormsReadPacketData,
	FormsReadPacketResponse,
	FormsReadPacketsData,
	FormsReadPacketsResponse,
	FormsSaveDocumentPdfData,
	FormsSaveDocumentPdfResponse,
	FormsUpdateIntakePacketData,
	FormsUpdateIntakePacketResponse,
	LoginLoginAccessTokenData,
	LoginLoginAccessTokenResponse,
	LoginRecoverPasswordData,
	LoginRecoverPasswordHtmlContentData,
	LoginRecoverPasswordHtmlContentResponse,
	LoginRecoverPasswordResponse,
	LoginResetPasswordData,
	LoginResetPasswordResponse,
	LoginTestTokenResponse,
	LogsReadLogsData,
	LogsReadLogsResponse,
	PatientsCreatePatientData,
	PatientsCreatePatientResponse,
	PatientsReadPatientData,
	PatientsReadPatientResponse,
	PatientsReadPatientsData,
	PatientsReadPatientsResponse,
	PrivateCreateUserData,
	PrivateCreateUserResponse,
	RemindersCreateReminderStatusData,
	RemindersCreateReminderStatusResponse,
	RemindersGetReminderStatusData,
	RemindersGetReminderStatusResponse,
	RemindersMarkReminderCompleteData,
	RemindersMarkReminderCompleteResponse,
	RemindersMarkReminderSeenData,
	RemindersMarkReminderSeenResponse,
	ReportsDownloadReportPdfResponse,
	ReportsGetAvgDurationResponse,
	ReportsGetIncompleteFormsResponse,
	ReportsGetIncompletePatientsResponse,
	ReportsGetSavedReportData,
	ReportsGetSavedReportResponse,
	ReportsListSavedReportsResponse,
	TemplatesAnalyzeResponse,
	TemplatesConfigureResponse,
	TemplatesCreateTemplateData,
	TemplatesCreateTemplateResponse,
	TemplatesDeleteTemplateData,
	TemplatesDeleteTemplateResponse,
	TemplatesReadTemplateData,
	TemplatesReadTemplateResponse,
	TemplatesReadTemplatesData,
	TemplatesReadTemplatesResponse,
	TemplatesUpdateTemplateData,
	TemplatesUpdateTemplateResponse,
	UsersCreateUserData,
	UsersCreateUserResponse,
	UsersDeleteUserData,
	UsersDeleteUserMeResponse,
	UsersDeleteUserResponse,
	UsersLogUserActionData,
	UsersLogUserActionResponse,
	UsersReadUserByIdData,
	UsersReadUserByIdResponse,
	UsersReadUserMeResponse,
	UsersReadUsersData,
	UsersReadUsersResponse,
	UsersRegisterUserData,
	UsersRegisterUserResponse,
	UsersUpdatePasswordMeData,
	UsersUpdatePasswordMeResponse,
	UsersUpdateUserData,
	UsersUpdateUserMeData,
	UsersUpdateUserMeResponse,
	UsersUpdateUserResponse,
	UtilsHealthCheckResponse,
	UtilsTestEmailData,
	UtilsTestEmailResponse,
} from "./types.gen";

export class AdminService {
	/**
	 * Read Folder
	 * Retrieve the SharePoint folder path
	 * configured by the admin.
	 * @returns AdminSettingsPublic Successful Response
	 * @throws ApiError
	 */
	public static readFolder(): CancelablePromise<AdminReadFolderResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/admin/settings/folder",
		});
	}

	/**
	 * Update Folder
	 * Update the SharePoint folder path
	 * configured by the admin.
	 * @param data The data for the request.
	 * @param data.folder
	 * @returns AdminSettingsPublic Successful Response
	 * @throws ApiError
	 */
	public static updateFolder(
		data: AdminUpdateFolderData,
	): CancelablePromise<AdminUpdateFolderResponse> {
		return __request(OpenAPI, {
			method: "PUT",
			url: "/api/v1/admin/settings/folder",
			query: {
				folder: data.folder,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}
}

export class FormsService {
	/**
	 * List Templates
	 * List all available intake form templates.
	 * @returns unknown Successful Response
	 * @throws ApiError
	 */
	public static listTemplates(): CancelablePromise<FormsListTemplatesResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/forms/templates",
		});
	}

	/**
	 * Create Intake Packet
	 * Generate a new intake packet (pre-fills and stores PDFs).
	 * @param data The data for the request.
	 * @param data.requestBody
	 * @returns IntakePacketPublic Successful Response
	 * @throws ApiError
	 */
	public static createIntakePacket(
		data: FormsCreateIntakePacketData,
	): CancelablePromise<FormsCreateIntakePacketResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/forms/packets",
			body: data.requestBody,
			mediaType: "application/json",
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Read Packets
	 * List intake packets for the current user.
	 * @param data The data for the request.
	 * @param data.skip
	 * @param data.limit
	 * @returns IntakePacketsPublic Successful Response
	 * @throws ApiError
	 */
	public static readPackets(
		data: FormsReadPacketsData = {},
	): CancelablePromise<FormsReadPacketsResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/forms/packets",
			query: {
				skip: data.skip,
				limit: data.limit,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Update Intake Packet
	 * Update an existing intake packet.
	 * @param data The data for the request.
	 * @param data.packetId
	 * @param data.requestBody
	 * @returns IntakePacketPublic Successful Response
	 * @throws ApiError
	 */
	public static updateIntakePacket(
		data: FormsUpdateIntakePacketData,
	): CancelablePromise<FormsUpdateIntakePacketResponse> {
		return __request(OpenAPI, {
			method: "PATCH",
			url: "/api/v1/forms/packets/{packet_id}",
			path: {
				packet_id: data.packetId,
			},
			body: data.requestBody,
			mediaType: "application/json",
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Read Packet
	 * Get a single intake packet with its documents.
	 * @param data The data for the request.
	 * @param data.packetId
	 * @returns IntakePacketPublic Successful Response
	 * @throws ApiError
	 */
	public static readPacket(
		data: FormsReadPacketData,
	): CancelablePromise<FormsReadPacketResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/forms/packets/{packet_id}",
			path: {
				packet_id: data.packetId,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Delete Packet
	 * Delete an intake packet and all its associated PDF files.
	 * @param data The data for the request.
	 * @param data.packetId
	 * @returns Message Successful Response
	 * @throws ApiError
	 */
	public static deletePacket(
		data: FormsDeletePacketData,
	): CancelablePromise<FormsDeletePacketResponse> {
		return __request(OpenAPI, {
			method: "DELETE",
			url: "/api/v1/forms/packets/{packet_id}",
			path: {
				packet_id: data.packetId,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Get Document Pdf
	 * Serve raw PDF bytes for the in-browser viewer.
	 * @param data The data for the request.
	 * @param data.packetId
	 * @param data.docId
	 * @returns unknown Successful Response
	 * @throws ApiError
	 */
	public static getDocumentPdf(
		data: FormsGetDocumentPdfData,
	): CancelablePromise<FormsGetDocumentPdfResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/forms/packets/{packet_id}/documents/{doc_id}/pdf",
			path: {
				packet_id: data.packetId,
				doc_id: data.docId,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Save Document Pdf
	 * Save a completed PDF (with signatures) back to the server.
	 * @param data The data for the request.
	 * @param data.packetId
	 * @param data.docId
	 * @returns unknown Successful Response
	 * @throws ApiError
	 */
	public static saveDocumentPdf(
		data: FormsSaveDocumentPdfData,
	): CancelablePromise<FormsSaveDocumentPdfResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/forms/packets/{packet_id}/documents/{doc_id}/save",
			path: {
				packet_id: data.packetId,
				doc_id: data.docId,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Read Document
	 * Get a single document record.
	 * @param data The data for the request.
	 * @param data.packetId
	 * @param data.docId
	 * @returns IntakeDocumentPublic Successful Response
	 * @throws ApiError
	 */
	public static readDocument(
		data: FormsReadDocumentData,
	): CancelablePromise<FormsReadDocumentResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/forms/packets/{packet_id}/documents/{doc_id}",
			path: {
				packet_id: data.packetId,
				doc_id: data.docId,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Add Documents To Packet
	 * Add new forms to an existing packet.
	 */
	public static addDocumentsToPacket(data: {
		packetId: string;
		requestBody: { template_ids: string[] };
	}): CancelablePromise<FormsReadDocumentResponse[]> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/forms/packets/{packet_id}/documents",
			path: {
				packet_id: data.packetId,
			},
			body: data.requestBody,
			mediaType: "application/json",
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Remove Document From Packet
	 * Remove a form from an existing packet.
	 */
	public static removeDocumentFromPacket(data: {
		packetId: string;
		docId: string;
	}): CancelablePromise<{ message: string }> {
		return __request(OpenAPI, {
			method: "DELETE",
			url: "/api/v1/forms/packets/{packet_id}/documents/{doc_id}",
			path: {
				packet_id: data.packetId,
				doc_id: data.docId,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}
}

export class LoginService {
	/**
	 * Login Access Token
	 * OAuth2 compatible token login, get an access token for future requests
	 * @param data The data for the request.
	 * @param data.formData
	 * @returns Token Successful Response
	 * @throws ApiError
	 */
	public static loginAccessToken(
		data: LoginLoginAccessTokenData,
	): CancelablePromise<LoginLoginAccessTokenResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/login/access-token",
			formData: data.formData,
			mediaType: "application/x-www-form-urlencoded",
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Test Token
	 * Test access token
	 * @returns UserPublic Successful Response
	 * @throws ApiError
	 */
	public static testToken(): CancelablePromise<LoginTestTokenResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/login/test-token",
		});
	}

	/**
	 * Recover Password
	 * Password Recovery
	 * @param data The data for the request.
	 * @param data.email
	 * @returns Message Successful Response
	 * @throws ApiError
	 */
	public static recoverPassword(
		data: LoginRecoverPasswordData,
	): CancelablePromise<LoginRecoverPasswordResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/password-recovery/{email}",
			path: {
				email: data.email,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Reset Password
	 * Reset password
	 * @param data The data for the request.
	 * @param data.requestBody
	 * @returns Message Successful Response
	 * @throws ApiError
	 */
	public static resetPassword(
		data: LoginResetPasswordData,
	): CancelablePromise<LoginResetPasswordResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/reset-password/",
			body: data.requestBody,
			mediaType: "application/json",
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Recover Password Html Content
	 * HTML Content for Password Recovery
	 * @param data The data for the request.
	 * @param data.email
	 * @returns string Successful Response
	 * @throws ApiError
	 */
	public static recoverPasswordHtmlContent(
		data: LoginRecoverPasswordHtmlContentData,
	): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/password-recovery-html-content/{email}",
			path: {
				email: data.email,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}
}

export class LogsService {
	/**
	 * Read Logs
	 * Retrieve logs.
	 * @param data The data for the request.
	 * @param data.user
	 * @param data.action
	 * @param data.startDate
	 * @param data.endDate
	 * @param data.skip
	 * @param data.limit
	 * @returns ActionLogsPublic Successful Response
	 * @throws ApiError
	 */
	public static readLogs(
		data: LogsReadLogsData = {},
	): CancelablePromise<LogsReadLogsResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/logs/",
			query: {
				user: data.user,
				action: data.action,
				start_date: data.startDate,
				end_date: data.endDate,
				skip: data.skip,
				limit: data.limit,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}
}

export class PatientsService {
	/**
	 * Read Patients
	 * Retrieve patients.
	 * @param data The data for the request.
	 * @param data.skip
	 * @param data.limit
	 * @returns PatientsPublic Successful Response
	 * @throws ApiError
	 */
	public static readPatients(
		data: PatientsReadPatientsData = {},
	): CancelablePromise<PatientsReadPatientsResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/patient/",
			query: {
				skip: data.skip,
				limit: data.limit,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Create Patient
	 * Create new patient.
	 * @param data The data for the request.
	 * @param data.requestBody
	 * @returns Patient Successful Response
	 * @throws ApiError
	 */
	public static createPatient(
		data: PatientsCreatePatientData,
	): CancelablePromise<PatientsCreatePatientResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/patient/",
			body: data.requestBody,
			mediaType: "application/json",
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Read Patient
	 * Get patient by EHR ID.
	 * @param data The data for the request.
	 * @param data.ehrId
	 * @returns Patient Successful Response
	 * @throws ApiError
	 */
	public static readPatient(
		data: PatientsReadPatientData,
	): CancelablePromise<PatientsReadPatientResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/patient/{ehr_id}",
			path: {
				ehr_id: data.ehrId,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}
}

export class PrivateService {
	/**
	 * Create User
	 * Create a new user.
	 * @param data The data for the request.
	 * @param data.requestBody
	 * @returns UserPublic Successful Response
	 * @throws ApiError
	 */
	public static createUser(
		data: PrivateCreateUserData,
	): CancelablePromise<PrivateCreateUserResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/private/users/",
			body: data.requestBody,
			mediaType: "application/json",
			errors: {
				422: "Validation Error",
			},
		});
	}
}

export class RemindersService {
	/**
	 * Create Reminder Status
	 * @param data The data for the request.
	 * @param data.patientEHRId
	 * @returns ReminderState Successful Response
	 * @throws ApiError
	 */
	public static createReminderStatus(
		data: RemindersCreateReminderStatusData,
	): CancelablePromise<RemindersCreateReminderStatusResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/reminders/new",
			query: {
				patient_ehr_id: data.patientEHRId,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Get Reminder Status
	 * @param data The data for the request.
	 * @param data.key
	 * @param data.ehrId
	 * @returns unknown Successful Response
	 * @throws ApiError
	 */
	public static getReminderStatus(
		data: RemindersGetReminderStatusData,
	): CancelablePromise<RemindersGetReminderStatusResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/reminders/{key}",
			path: {
				key: data.key,
			},
			query: {
				ehr_id: data.ehrId,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Mark Reminder Complete
	 * @param data The data for the request.
	 * @param data.key
	 * @param data.requestBody
	 * @returns unknown Successful Response
	 * @throws ApiError
	 */
	public static markReminderComplete(
		data: RemindersMarkReminderCompleteData,
	): CancelablePromise<RemindersMarkReminderCompleteResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/reminders/{key}/complete",
			path: {
				key: data.key,
			},
			body: data.requestBody,
			mediaType: "application/json",
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Mark Reminder Seen
	 * @param data The data for the request.
	 * @param data.requestBody
	 * @returns unknown Successful Response
	 * @throws ApiError
	 */
	public static markReminderSeen(
		data: RemindersMarkReminderSeenData,
	): CancelablePromise<RemindersMarkReminderSeenResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/reminders/seen",
			body: data.requestBody,
			mediaType: "application/json",
			errors: {
				422: "Validation Error",
			},
		});
	}
}

export class ReportsService {
	/**
	 * Get Avg Duration
	 * Endpoint to get the average duration in hours between intake packet creation
	 * and reminder completion.
	 * @returns unknown Successful Response
	 * @throws ApiError
	 */
	public static getAvgDuration(): CancelablePromise<ReportsGetAvgDurationResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/reports/avg-duration",
		});
	}

	/**
	 * Get Incomplete Patients
	 * Endpoint to get the list of patients who have incomplete forms
	 * @returns unknown Successful Response
	 * @throws ApiError
	 */
	public static getIncompletePatients(): CancelablePromise<ReportsGetIncompletePatientsResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/reports/incomplete-patients",
		});
	}

	/**
	 * Get Incomplete Forms
	 * Endpoint to get the summary of forms that have not yet
	 * been completed (i.e. status != COMPLETED or LINKED)
	 * @returns unknown Successful Response
	 * @throws ApiError
	 */
	public static getIncompleteForms(): CancelablePromise<ReportsGetIncompleteFormsResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/reports/incomplete-forms",
		});
	}

	/**
	 * Download Report Pdf
	 * Generate and download a PDF report on-demand.
	 * @returns unknown Successful Response
	 * @throws ApiError
	 */
	public static downloadReportPdf(): CancelablePromise<ReportsDownloadReportPdfResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/reports/download-pdf",
		});
	}

	/**
	 * List Saved Reports
	 * List all generated PDF reports.
	 * @returns string Successful Response
	 * @throws ApiError
	 */
	public static listSavedReports(): CancelablePromise<ReportsListSavedReportsResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/reports/saved-reports",
		});
	}

	/**
	 * Get Saved Report
	 * Download a specific generated PDF report.
	 * @param data The data for the request.
	 * @param data.filename
	 * @returns unknown Successful Response
	 * @throws ApiError
	 */
	public static getSavedReport(
		data: ReportsGetSavedReportData,
	): CancelablePromise<ReportsGetSavedReportResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/reports/saved-reports/{filename}",
			path: {
				filename: data.filename,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}
}

export class TemplatesService {
	/**
	 * Read Templates
	 * Retrieve templates.
	 * @param data The data for the request.
	 * @param data.skip
	 * @param data.limit
	 * @returns TemplatesPublic Successful Response
	 * @throws ApiError
	 */
	public static readTemplates(
		data: TemplatesReadTemplatesData = {},
	): CancelablePromise<TemplatesReadTemplatesResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/templates/",
			query: {
				skip: data.skip,
				limit: data.limit,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Create Template
	 * Create a new template with a PDF file upload.
	 * @param data The data for the request.
	 * @param data.formData
	 * @returns TemplatePublic Successful Response
	 * @throws ApiError
	 */
	public static createTemplate(
		data: TemplatesCreateTemplateData,
	): CancelablePromise<TemplatesCreateTemplateResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/templates/",
			formData: data.formData,
			mediaType: "multipart/form-data",
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Read Template
	 * Get template by ID.
	 * @param data The data for the request.
	 * @param data.id
	 * @returns binary Return the PDF file
	 * @throws ApiError
	 */
	public static readTemplate(
		data: TemplatesReadTemplateData,
	): CancelablePromise<TemplatesReadTemplateResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/templates/{id}",
			path: {
				id: data.id,
			},
			errors: {
				404: "Template not found",
				422: "Validation Error",
			},
		});
	}

	/**
	 * Update Template
	 * Update an existing template.
	 * @param data The data for the request.
	 * @param data.id
	 * @param data.formData
	 * @returns TemplatePublic Successful Response
	 * @throws ApiError
	 */
	public static updateTemplate(
		data: TemplatesUpdateTemplateData,
	): CancelablePromise<TemplatesUpdateTemplateResponse> {
		return __request(OpenAPI, {
			method: "PUT",
			url: "/api/v1/templates/{id}",
			path: {
				id: data.id,
			},
			formData: data.formData,
			mediaType: "multipart/form-data",
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Delete Template
	 * Delete a template.
	 * @param data The data for the request.
	 * @param data.id
	 * @returns unknown Successful Response
	 * @throws ApiError
	 */
	public static deleteTemplate(
		data: TemplatesDeleteTemplateData,
	): CancelablePromise<TemplatesDeleteTemplateResponse> {
		return __request(OpenAPI, {
			method: "DELETE",
			url: "/api/v1/templates/{id}",
			path: {
				id: data.id,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Analyze Template
	 * Analyze an uploaded PDF to extract its AcroForm fields.
	 */
	public static analyzeTemplate(data: {
		id: string;
	}): CancelablePromise<TemplatesAnalyzeResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/templates/{id}/analyze",
			path: {
				id: data.id,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Configure Template
	 * Save field mappings and activate an uploaded template for use in packets.
	 */
	public static configureTemplate(data: {
		id: string;
		requestBody: Record<string, unknown>;
	}): CancelablePromise<TemplatesConfigureResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/templates/{id}/configure",
			path: {
				id: data.id,
			},
			body: data.requestBody,
			mediaType: "application/json",
			errors: {
				422: "Validation Error",
			},
		});
	}
}

export class UsersService {
	/**
	 * Read Users
	 * Retrieve users.
	 * @param data The data for the request.
	 * @param data.skip
	 * @param data.limit
	 * @returns UsersPublic Successful Response
	 * @throws ApiError
	 */
	public static readUsers(
		data: UsersReadUsersData = {},
	): CancelablePromise<UsersReadUsersResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/users/",
			query: {
				skip: data.skip,
				limit: data.limit,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Create User
	 * Create new user.
	 * @param data The data for the request.
	 * @param data.requestBody
	 * @returns UserPublic Successful Response
	 * @throws ApiError
	 */
	public static createUser(
		data: UsersCreateUserData,
	): CancelablePromise<UsersCreateUserResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/users/",
			body: data.requestBody,
			mediaType: "application/json",
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Read User Me
	 * Get current user.
	 * @returns UserPublic Successful Response
	 * @throws ApiError
	 */
	public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/users/me",
		});
	}

	/**
	 * Delete User Me
	 * Delete own user.
	 * @returns Message Successful Response
	 * @throws ApiError
	 */
	public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
		return __request(OpenAPI, {
			method: "DELETE",
			url: "/api/v1/users/me",
		});
	}

	/**
	 * Update User Me
	 * Update own user.
	 * @param data The data for the request.
	 * @param data.requestBody
	 * @returns UserPublic Successful Response
	 * @throws ApiError
	 */
	public static updateUserMe(
		data: UsersUpdateUserMeData,
	): CancelablePromise<UsersUpdateUserMeResponse> {
		return __request(OpenAPI, {
			method: "PATCH",
			url: "/api/v1/users/me",
			body: data.requestBody,
			mediaType: "application/json",
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Update Password Me
	 * Update own password.
	 * @param data The data for the request.
	 * @param data.requestBody
	 * @returns Message Successful Response
	 * @throws ApiError
	 */
	public static updatePasswordMe(
		data: UsersUpdatePasswordMeData,
	): CancelablePromise<UsersUpdatePasswordMeResponse> {
		return __request(OpenAPI, {
			method: "PATCH",
			url: "/api/v1/users/me/password",
			body: data.requestBody,
			mediaType: "application/json",
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Log User Action
	 * Log a user defined action.
	 * @param data The data for the request.
	 * @param data.requestBody
	 * @returns Message Successful Response
	 * @throws ApiError
	 */
	public static logUserAction(
		data: UsersLogUserActionData,
	): CancelablePromise<UsersLogUserActionResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/users/me/log-action",
			body: data.requestBody,
			mediaType: "application/json",
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Register User
	 * Create new user without the need to be logged in.
	 * @param data The data for the request.
	 * @param data.requestBody
	 * @returns UserPublic Successful Response
	 * @throws ApiError
	 */
	public static registerUser(
		data: UsersRegisterUserData,
	): CancelablePromise<UsersRegisterUserResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/users/signup",
			body: data.requestBody,
			mediaType: "application/json",
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Read User By Id
	 * Get a specific user by id.
	 * @param data The data for the request.
	 * @param data.userId
	 * @returns UserPublic Successful Response
	 * @throws ApiError
	 */
	public static readUserById(
		data: UsersReadUserByIdData,
	): CancelablePromise<UsersReadUserByIdResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/users/{user_id}",
			path: {
				user_id: data.userId,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Update User
	 * Update a user.
	 * @param data The data for the request.
	 * @param data.userId
	 * @param data.requestBody
	 * @returns UserPublic Successful Response
	 * @throws ApiError
	 */
	public static updateUser(
		data: UsersUpdateUserData,
	): CancelablePromise<UsersUpdateUserResponse> {
		return __request(OpenAPI, {
			method: "PATCH",
			url: "/api/v1/users/{user_id}",
			path: {
				user_id: data.userId,
			},
			body: data.requestBody,
			mediaType: "application/json",
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Delete User
	 * Delete a user.
	 * @param data The data for the request.
	 * @param data.userId
	 * @returns Message Successful Response
	 * @throws ApiError
	 */
	public static deleteUser(
		data: UsersDeleteUserData,
	): CancelablePromise<UsersDeleteUserResponse> {
		return __request(OpenAPI, {
			method: "DELETE",
			url: "/api/v1/users/{user_id}",
			path: {
				user_id: data.userId,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}
}

export class UtilsService {
	/**
	 * Test Email
	 * Test emails.
	 * @param data The data for the request.
	 * @param data.emailTo
	 * @returns Message Successful Response
	 * @throws ApiError
	 */
	public static testEmail(
		data: UtilsTestEmailData,
	): CancelablePromise<UtilsTestEmailResponse> {
		return __request(OpenAPI, {
			method: "POST",
			url: "/api/v1/utils/test-email/",
			query: {
				email_to: data.emailTo,
			},
			errors: {
				422: "Validation Error",
			},
		});
	}

	/**
	 * Health Check
	 * @returns boolean Successful Response
	 * @throws ApiError
	 */
	public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
		return __request(OpenAPI, {
			method: "GET",
			url: "/api/v1/utils/health-check/",
		});
	}
}
