// This file is auto-generated by @hey-api/openapi-ts

export type ActionLog = {
    action: string;
};

export type ActionLogPublic = {
    user: string;
    action: string;
    timestamp: string;
};

export type ActionLogsPublic = {
    data: Array<ActionLogPublic>;
    count: number;
};

export type AdminSettingsPublic = {
    name: string;
    value: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_templates_create_template = {
    file: (Blob | File);
};

export type Body_templates_update_template = {
    file?: ((Blob | File) | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IntakeDocumentPublic = {
    id: string;
    template_id: string;
    form_name: string;
    category: string;
    filename: string;
    status: string;
    packet_id: string;
    created_at?: (string | null);
};

export type IntakePacketCreate = {
    patient_id_number: string;
    patient_name: string;
    facility: string;
    admission_date: string;
    counselor_name: string;
    template_ids: Array<(string)>;
};

export type IntakePacketPublic = {
    patient_id_number: string;
    patient_name: string;
    facility: string;
    admission_date: string;
    counselor_name: string;
    id: string;
    status: string;
    owner_id: string;
    created_at?: (string | null);
    documents?: Array<IntakeDocumentPublic>;
};

export type IntakePacketsPublic = {
    data: Array<IntakePacketPublic>;
    count: number;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type Patient = {
    ehr_id: number;
    id?: string;
    created_at?: (string | null);
    counselorId?: (string | null);
};

export type PatientCreate = {
    ehr_id: number;
};

export type PatientPublic = {
    ehr_id: number;
    id: string;
    created_at?: (string | null);
};

export type PatientsPublic = {
    data: Array<PatientPublic>;
    count: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ReminderPatientPayload = {
    ehr_id: number;
};

/**
 * Per-patient (ehr_id), per-reminder state.
 */
export type ReminderState = {
    key: string;
    completed_at?: (string | null);
    seen_at?: (string | null);
    id?: string;
    patient_ehr_id: number;
};

export type TemplatePublic = {
    file_id: string;
    file_name: string;
    file_modified?: (string | null);
    file_owner: string;
    category?: string;
    template_config?: (string | null);
};

export type TemplatesPublic = {
    data: Array<TemplatePublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
    role?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AdminReadFolderResponse = (AdminSettingsPublic);

export type AdminUpdateFolderData = {
    folder: string;
};

export type AdminUpdateFolderResponse = (AdminSettingsPublic);

export type FormsListTemplatesResponse = (unknown);

export type FormsCreateIntakePacketData = {
    requestBody: IntakePacketCreate;
};

export type FormsCreateIntakePacketResponse = (IntakePacketPublic);

export type FormsReadPacketsData = {
    limit?: number;
    skip?: number;
};

export type FormsReadPacketsResponse = (IntakePacketsPublic);

export type FormsUpdateIntakePacketData = {
    packetId: string;
    requestBody: {
        [key: string]: unknown;
    };
};

export type FormsUpdateIntakePacketResponse = (IntakePacketPublic);

export type FormsReadPacketData = {
    packetId: string;
};

export type FormsReadPacketResponse = (IntakePacketPublic);

export type FormsDeletePacketData = {
    packetId: string;
};

export type FormsDeletePacketResponse = (Message);

export type FormsGetDocumentPdfData = {
    docId: string;
    packetId: string;
};

export type FormsGetDocumentPdfResponse = (unknown);

export type FormsSaveDocumentPdfData = {
    docId: string;
    packetId: string;
};

export type FormsSaveDocumentPdfResponse = (unknown);

export type FormsReadDocumentData = {
    docId: string;
    packetId: string;
};

export type FormsReadDocumentResponse = (IntakeDocumentPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type LogsReadLogsData = {
    action?: (string | null);
    endDate?: (string | null);
    limit?: number;
    skip?: number;
    startDate?: (string | null);
    user?: (string | null);
};

export type LogsReadLogsResponse = (ActionLogsPublic);

export type PatientsReadPatientsData = {
    limit?: number;
    skip?: number;
};

export type PatientsReadPatientsResponse = (PatientsPublic);

export type PatientsCreatePatientData = {
    requestBody: PatientCreate;
};

export type PatientsCreatePatientResponse = (Patient);

export type PatientsReadPatientData = {
    ehrId: number;
};

export type PatientsReadPatientResponse = (Patient);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RemindersCreateReminderStatusData = {
    patientEHRId: number;
};

export type RemindersCreateReminderStatusResponse = (ReminderState);

export type RemindersGetReminderStatusData = {
    key: string;
    ehrId: number;
};

export type RemindersGetReminderStatusResponse = ({
    [key: string]: unknown;
});

export type RemindersMarkReminderCompleteData = {
    key: string;
    requestBody: ReminderPatientPayload;
};

export type RemindersMarkReminderCompleteResponse = ({
    [key: string]: unknown;
});

export type RemindersMarkReminderSeenData = {
    requestBody: ReminderPatientPayload;
};

export type RemindersMarkReminderSeenResponse = ({
    [key: string]: unknown;
});

export type ReportsGetAvgDurationResponse = (unknown);

export type ReportsGetIncompletePatientsResponse = (unknown);

export type ReportsGetIncompleteFormsResponse = (unknown);

export type ReportsDownloadReportPdfResponse = (unknown);

export type ReportsListSavedReportsResponse = (Array<(string)>);

export type ReportsGetSavedReportData = {
    filename: string;
};

export type ReportsGetSavedReportResponse = (unknown);

export type TemplatesReadTemplatesData = {
    limit?: number;
    skip?: number;
};

export type TemplatesReadTemplatesResponse = (TemplatesPublic);

export type TemplatesCreateTemplateData = {
    formData: Body_templates_create_template;
};

export type TemplatesCreateTemplateResponse = (TemplatePublic);

export type TemplatesReadTemplateData = {
    id: string;
};

export type TemplatesReadTemplateResponse = ((Blob | File));

export type TemplatesUpdateTemplateData = {
    formData?: Body_templates_update_template;
    id: string;
};

export type TemplatesUpdateTemplateResponse = (TemplatePublic);

export type TemplatesDeleteTemplateData = {
    id: string;
};

export type TemplatesDeleteTemplateResponse = (unknown);

export type TemplatesAnalyzeResponse = {
    template_id: string;
    file_name: string;
    fields: Array<{
        field_id: string;
        acroform_name: string;
        field_type: string;
        page: number;
        x: number;
        y: number;
        width: number;
        height: number;
        auto_map_key: string;
        label: string;
        confidence?: number;
    }>;
    auto_map_keys: Array<{
        key: string;
        label: string;
    }>;
};

export type TemplatesConfigureResponse = {
    success: boolean;
    template_id: string;
    form_name: string;
    category: string;
    field_count: number;
};

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersLogUserActionData = {
    requestBody: ActionLog;
};

export type UsersLogUserActionResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);