"""template unification 3/29

Revision ID: 40b24963db18
Revises: fe56fa70289e
Create Date: 2026-03-29 19:48:48.872518

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from app.core.config import settings


# revision identifiers, used by Alembic.
revision = '40b24963db18'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminsettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('useractionlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_useractionlog_action'), 'useractionlog', ['action'], unique=False)
    op.create_index(op.f('ix_useractionlog_user'), 'useractionlog', ['user'], unique=False)
    op.create_table('weeklyreport',
    sa.Column('reportEmail', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('avgCompletionTime', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intakepacket',
    sa.Column('patient_id_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('patient_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('facility', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('admission_date', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('counselor_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('ehr_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('counselorId', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['counselorId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ehr_id')
    )
    op.create_table('template',
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('file_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_owner', sa.Uuid(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('template_config', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['file_owner'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('intakedocument',
    sa.Column('template_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('form_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('packet_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['intakepacket.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminderstate',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_ehr_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_ehr_id'], ['patient.ehr_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_ehr_id', 'key', name='uq_reminderstate_ehr_key')
    )
    op.create_index(op.f('ix_reminderstate_key'), 'reminderstate', ['key'], unique=False)
    op.create_index(op.f('ix_reminderstate_patient_ehr_id'), 'reminderstate', ['patient_ehr_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminderstate_patient_ehr_id'), table_name='reminderstate')
    op.drop_index(op.f('ix_reminderstate_key'), table_name='reminderstate')
    op.drop_table('reminderstate')
    op.drop_table('intakedocument')
    op.drop_table('template')
    op.drop_table('patient')
    op.drop_table('intakepacket')
    op.drop_table('weeklyreport')
    op.drop_index(op.f('ix_useractionlog_user'), table_name='useractionlog')
    op.drop_index(op.f('ix_useractionlog_action'), table_name='useractionlog')
    op.drop_table('useractionlog')
    op.drop_table('adminsettings')
    # ### end Alembic commands ###
