/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTemplatesRouteImport } from './routes/_layout/templates'
import { Route as LayoutStaffDashboardRouteImport } from './routes/_layout/staff-dashboard'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutNewIntakeRouteImport } from './routes/_layout/new-intake'
import { Route as LayoutFormsRouteImport } from './routes/_layout/forms'
import { Route as LayoutFormSignerRouteImport } from './routes/_layout/form-signer'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTemplatesRoute = LayoutTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStaffDashboardRoute = LayoutStaffDashboardRouteImport.update({
  id: '/staff-dashboard',
  path: '/staff-dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNewIntakeRoute = LayoutNewIntakeRouteImport.update({
  id: '/new-intake',
  path: '/new-intake',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormsRoute = LayoutFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormSignerRoute = LayoutFormSignerRouteImport.update({
  id: '/form-signer',
  path: '/form-signer',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/form-signer': typeof LayoutFormSignerRoute
  '/forms': typeof LayoutFormsRoute
  '/new-intake': typeof LayoutNewIntakeRoute
  '/settings': typeof LayoutSettingsRoute
  '/staff-dashboard': typeof LayoutStaffDashboardRoute
  '/templates': typeof LayoutTemplatesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/form-signer': typeof LayoutFormSignerRoute
  '/forms': typeof LayoutFormsRoute
  '/new-intake': typeof LayoutNewIntakeRoute
  '/settings': typeof LayoutSettingsRoute
  '/staff-dashboard': typeof LayoutStaffDashboardRoute
  '/templates': typeof LayoutTemplatesRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/form-signer': typeof LayoutFormSignerRoute
  '/_layout/forms': typeof LayoutFormsRoute
  '/_layout/new-intake': typeof LayoutNewIntakeRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/staff-dashboard': typeof LayoutStaffDashboardRoute
  '/_layout/templates': typeof LayoutTemplatesRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/form-signer'
    | '/forms'
    | '/new-intake'
    | '/settings'
    | '/staff-dashboard'
    | '/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/form-signer'
    | '/forms'
    | '/new-intake'
    | '/settings'
    | '/staff-dashboard'
    | '/templates'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/dashboard'
    | '/_layout/form-signer'
    | '/_layout/forms'
    | '/_layout/new-intake'
    | '/_layout/settings'
    | '/_layout/staff-dashboard'
    | '/_layout/templates'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/templates': {
      id: '/_layout/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof LayoutTemplatesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/staff-dashboard': {
      id: '/_layout/staff-dashboard'
      path: '/staff-dashboard'
      fullPath: '/staff-dashboard'
      preLoaderRoute: typeof LayoutStaffDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/new-intake': {
      id: '/_layout/new-intake'
      path: '/new-intake'
      fullPath: '/new-intake'
      preLoaderRoute: typeof LayoutNewIntakeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/forms': {
      id: '/_layout/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof LayoutFormsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form-signer': {
      id: '/_layout/form-signer'
      path: '/form-signer'
      fullPath: '/form-signer'
      preLoaderRoute: typeof LayoutFormSignerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutFormSignerRoute: typeof LayoutFormSignerRoute
  LayoutFormsRoute: typeof LayoutFormsRoute
  LayoutNewIntakeRoute: typeof LayoutNewIntakeRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStaffDashboardRoute: typeof LayoutStaffDashboardRoute
  LayoutTemplatesRoute: typeof LayoutTemplatesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutFormSignerRoute: LayoutFormSignerRoute,
  LayoutFormsRoute: LayoutFormsRoute,
  LayoutNewIntakeRoute: LayoutNewIntakeRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStaffDashboardRoute: LayoutStaffDashboardRoute,
  LayoutTemplatesRoute: LayoutTemplatesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
